export const defaultExercises = [
  {
    name: 'Barbell Bench Press',
    description: 'Classic chest exercise',
    muscle_group: 'Chest',
    equipment: 'Barbell',
    instructions: '1. Lie on bench with feet flat on floor\n2. Grip bar slightly wider than shoulder width\n3. Lower bar to chest with control\n4. Press bar up until arms are extended\n5. Keep shoulder blades retracted throughout',
    is_custom: false,
  },
  {
    name: 'Barbell Squat',
    description: 'Compound lower body exercise',
    muscle_group: 'Legs',
    equipment: 'Barbell',
    instructions: '1. Position bar on upper back\n2. Stand with feet shoulder-width apart\n3. Descend by bending knees and hips\n4. Go down until thighs are parallel to floor\n5. Drive through heels to stand up',
    is_custom: false,
  },
  {
    name: 'Deadlift',
    description: 'Full body compound lift',
    muscle_group: 'Back',
    equipment: 'Barbell',
    instructions: '1. Stand with feet hip-width apart, bar over mid-foot\n2. Bend down and grip bar\n3. Keep back straight, chest up\n4. Drive through heels, extend hips and knees\n5. Stand tall, then lower with control',
    is_custom: false,
  },
  {
    name: 'Pull-ups',
    description: 'Bodyweight back exercise',
    muscle_group: 'Back',
    equipment: 'Pull-up Bar',
    instructions: '1. Hang from bar with overhand grip\n2. Pull yourself up until chin clears bar\n3. Lower with control to full extension\n4. Keep core engaged throughout',
    is_custom: false,
  },
  {
    name: 'Overhead Press',
    description: 'Shoulder strength builder',
    muscle_group: 'Shoulders',
    equipment: 'Barbell',
    instructions: '1. Stand with bar at shoulder height\n2. Grip bar slightly wider than shoulders\n3. Press bar overhead until arms are extended\n4. Lower with control to shoulders\n5. Keep core tight throughout',
    is_custom: false,
  },
  {
    name: 'Barbell Row',
    description: 'Back thickness builder',
    muscle_group: 'Back',
    equipment: 'Barbell',
    instructions: '1. Bend at hips, keep back straight\n2. Grip bar with hands shoulder-width\n3. Pull bar to lower chest/upper abdomen\n4. Squeeze shoulder blades together\n5. Lower with control',
    is_custom: false,
  },
  {
    name: 'Dumbbell Bicep Curl',
    description: 'Isolation exercise for biceps',
    muscle_group: 'Arms',
    equipment: 'Dumbbells',
    instructions: '1. Stand with dumbbells at sides\n2. Keep elbows close to body\n3. Curl weights up toward shoulders\n4. Squeeze biceps at top\n5. Lower with control',
    is_custom: false,
  },
  {
    name: 'Tricep Dips',
    description: 'Bodyweight tricep exercise',
    muscle_group: 'Arms',
    equipment: 'Dip Bars',
    instructions: '1. Grip bars with arms extended\n2. Lower body by bending elbows\n3. Go down until upper arms are parallel to floor\n4. Press back up to starting position\n5. Keep chest upright',
    is_custom: false,
  },
  {
    name: 'Lunges',
    description: 'Unilateral leg exercise',
    muscle_group: 'Legs',
    equipment: 'Bodyweight/Dumbbells',
    instructions: '1. Step forward with one leg\n2. Lower hips until both knees are bent at 90 degrees\n3. Push back to starting position\n4. Alternate legs\n5. Keep torso upright',
    is_custom: false,
  },
  {
    name: 'Plank',
    description: 'Core stability exercise',
    muscle_group: 'Core',
    equipment: 'Bodyweight',
    instructions: '1. Start in push-up position\n2. Rest on forearms instead of hands\n3. Keep body in straight line\n4. Engage core and glutes\n5. Hold for desired time',
    is_custom: false,
  },
  {
    name: 'Leg Press',
    description: 'Machine-based leg exercise',
    muscle_group: 'Legs',
    equipment: 'Leg Press Machine',
    instructions: '1. Sit in machine with feet on platform\n2. Release safety and lower weight\n3. Bend knees until they reach 90 degrees\n4. Press through heels to extend legs\n5. Do not lock knees at top',
    is_custom: false,
  },
  {
    name: 'Lat Pulldown',
    description: 'Back width builder',
    muscle_group: 'Back',
    equipment: 'Cable Machine',
    instructions: '1. Sit at lat pulldown machine\n2. Grip bar wider than shoulders\n3. Pull bar down to upper chest\n4. Squeeze shoulder blades together\n5. Return to start with control',
    is_custom: false,
  },
];
